services:
  SoulMaskServer:
    container_name: SoulMaskServer
    image: wekod/soulmask-server:latest
    restart: unless-stopped
    volumes: 
        - ./data:/SoulMaskServer
    ports:
      - target: 8777
        published: 8777
        protocol: udp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 18888
        published: 18888
        protocol: tcp
        mode: host
    environment:
        - SERVER_HOSTNAME=Wekod Docker Server
        - MAX_PLAYER=20
        - SERVER_PORT=8777 
        - SERVER_QUERYPORT=27015 
        - SERVER_ECHOPORT=18888